bind-key C-b last-window

unbind %
bind | split-window -h
bind - split-window -v

set -g default-terminal "screen-256color"
set-option -g history-limit 100000

set -g base-index 1

set -g terminal-overrides '*:sitm@,ritm@'
